version: 2.1

jobs:
  build:
    docker:
      - image: adoptopenjdk
    steps:
      - checkout
      - run: ./gradlew build
  test:
    steps:
      - checkout
      - run: ./gradlew test
workflows:
  jobs:
    - build
    - test