version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
        auth:
          username: satouaaaaa
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: gradle build
  test:
    docker:
      - image: circleci/openjdk:17-jdk
        auth:
          username: satouaaaaa
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: gradle test

workflows:
  build_and_test:
    jobs:
      - build
      - test
