orbs:
  docker: circleci/docker@1.7.0

jobs:
  test:
    docker:
    - image: cimg/openjdk:stable
    steps:
      - checkout
      - run: |
          gradle test

workflows:
  version: 2
  test:
    jobs:
      - test