version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run: gradle build -x test
      - run:
          name: run test
          command: gradle test