version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    steps:
      - checkout
      - run: gradle build
  test:
    steps:
      - checkout
      - run: gradle test

workflows:
  build_and_test:
    jobs:
      - build
      - test

